name: Config Entity Source
description: Config entity source plugin for the Translation Management system.
package: Translation Management
# core: 8.x
type: module

dependencies:
 - tmgmt
 - config_translation
 - block

# Information added by Drupal.org packaging script on 2016-03-29
version: '8.x-1.0-rc1'
core: '8.x'
project: 'tmgmt'
datestamp: 1459294445
