# image_effects module schema

# Schema for module settings.

image_effects.settings:
  type: config_object
  label: 'Image Effects settings'
  mapping:
    color_selector:
      type: mapping
      label: 'Color selector plugin'
      mapping:
        plugin_id:
          type: string
          label: 'Selected plugin id'
        plugin_settings:
          type: sequence
          label: 'Plugin settings'
          sequence:
            type: image_effects.plugin.color_selector.[%key]
    image_selector:
      type: mapping
      label: 'Image selector plugin'
      mapping:
        plugin_id:
          type: string
          label: 'Selected plugin id'
        plugin_settings:
          type: sequence
          label: 'Plugins settings'
          sequence:
            type: image_effects.plugin.image_selector.[%key]
    font_selector:
      type: mapping
      label: 'Font selector plugin'
      mapping:
        plugin_id:
          type: string
          label: 'Selected plugin id'
        plugin_settings:
          type: sequence
          label: 'Plugins settings'
          sequence:
            type: image_effects.plugin.font_selector.[%key]

# Schema for image_effects plugins settings.

image_effects.plugin.color_selector.*:
  type: mapping
  label: 'Color selector plugin settings'

image_effects.plugin.color_selector.html_color:
  type: mapping
  label: 'HTML color element'

image_effects.plugin.color_selector.farbtastic:
  type: mapping
  label: 'Farbtastic color picker'

image_effects.plugin.image_selector.*:
  type: mapping
  label: 'Image selector plugin settings'

image_effects.plugin.image_selector.basic:
  type: mapping
  label: 'Basic'

image_effects.plugin.image_selector.dropdown:
  type: mapping
  label: 'Dropdown'
  mapping:
    path:
      type: string
      label: 'Path where image files can be found'

image_effects.plugin.font_selector.*:
  type: mapping
  label: 'Font selector plugin settings'

image_effects.plugin.font_selector.basic:
  type: mapping
  label: 'Basic'

image_effects.plugin.font_selector.dropdown:
  type: mapping
  label: 'Dropdown'
  mapping:
    path:
      type: string
      label: 'Path where font files can be found'

# Image effects settings

image.effect.image_effects_auto_orient:
  type: mapping
  label: 'Automatically correct orientation'
  mapping:
    scan_exif:
      type: boolean
      label: 'Scan EXIF data when calculating styled image dimensions'

image.effect.image_effects_brightness:
  type: mapping
  label: 'Adjust image brightness'
  mapping:
    level:
      type: integer
      label: 'Level'

image.effect.image_effects_color_shift:
  type: mapping
  label: 'Shift image colors'
  mapping:
    RGB:
      type: string
      label: 'RGB color shift'

image.effect.image_effects_contrast:
  type: mapping
  label: 'Adjust image contrast'
  mapping:
    level:
      type: integer
      label: 'Level'

image.effect.image_effects_set_canvas:
  type: mapping
  label: 'Set canvas image effect'
  mapping:
    canvas_size:
      type: string
      label: 'Canvas sizing, exact or relative'
    canvas_color:
      type: string
      label: 'RGBA color of the canvas'
    exact:
      type: mapping
      mapping:
        width:
          type: string
          label: 'Exact width in px'
        height:
          type: string
          label: 'Exact height in px'
        placement:
          type: string
          label: 'Position of the source image on the canvas'
        x_offset:
          type: integer
          label: 'x offset vs placement'
        y_offset:
          type: integer
          label: 'y offset vs placement'
    relative:
      type: mapping
      mapping:
        left:
          type: integer
          label: 'Left margin in px'
        right:
          type: integer
          label: 'Right margin in px'
        top:
          type: integer
          label: 'Top margin in px'
        bottom:
          type: integer
          label: 'Bottom margin in px'

# The strip metadata effect has no settings.
image.effect.image_effects_strip_metadata:
  type: sequence

image.effect.image_effects_watermark:
  type: mapping
  label: 'Watermark image effect'
  mapping:
    placement:
      type: string
      label: 'Position of the watermark'
    x_offset:
      type: integer
      label: 'x offset'
    y_offset:
      type: integer
      label: 'y offset'
    opacity:
      type: integer
      label: 'opacity'
    watermark_image:
      type: string
      label: 'watermark image path'
